---
base_url: "https://mysite.com"
static_dir: "static"
per_page: 25

# Each entry can have multiple collection of tags (list of strings) in addition to the
# categories. For instance, a directory of fonts could have multiple meaningful
# tag collections per entry such as:
# types = [serif, sans-serif, display, script]
# mood = [retro, distressed, cool]
# tag = [yep, nope, etc]
taxonomies: ["type"]

site_name: "Resources for FOSS Maintainers"
site_description: "A directory of resources for FOSS maintainers"
page_title: "{category} - Directory of resources for FOSS maintainers."
meta_description: "Directory of {category} resources for FOSS maintainers."
